version: '3.8'

services:
  app:
    build: .
    ports:
      - "10000:10000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/paircode
      - PORT=10000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
